package com.fortune.jisx.sql.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.fortune.jisx.sql.greendao.UserEntity;
import com.fortune.jisx.sql.greendao.DownloadEntity;

import com.fortune.jisx.sql.greendao.UserEntityDao;
import com.fortune.jisx.sql.greendao.DownloadEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userEntityDaoConfig;
    private final DaoConfig downloadEntityDaoConfig;

    private final UserEntityDao userEntityDao;
    private final DownloadEntityDao downloadEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        downloadEntityDaoConfig = daoConfigMap.get(DownloadEntityDao.class).clone();
        downloadEntityDaoConfig.initIdentityScope(type);

        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);
        downloadEntityDao = new DownloadEntityDao(downloadEntityDaoConfig, this);

        registerDao(UserEntity.class, userEntityDao);
        registerDao(DownloadEntity.class, downloadEntityDao);
    }
    
    public void clear() {
        userEntityDaoConfig.clearIdentityScope();
        downloadEntityDaoConfig.clearIdentityScope();
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

    public DownloadEntityDao getDownloadEntityDao() {
        return downloadEntityDao;
    }

}
