package com.fortune.jisx.sql.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LOG_ENTITY".
*/
public class LogEntityDao extends AbstractDao<LogEntity, Long> {

    public static final String TABLENAME = "LOG_ENTITY";

    /**
     * Properties of entity LogEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ClassName = new Property(1, String.class, "className", false, "CLASS_NAME");
        public final static Property Message = new Property(2, String.class, "message", false, "MESSAGE");
        public final static Property DeviceBrand = new Property(3, String.class, "deviceBrand", false, "DEVICE_BRAND");
        public final static Property Model = new Property(4, String.class, "model", false, "MODEL");
        public final static Property Sdk = new Property(5, int.class, "sdk", false, "SDK");
        public final static Property Imei = new Property(6, String.class, "imei", false, "IMEI");
        public final static Property SystemVersion = new Property(7, String.class, "systemVersion", false, "SYSTEM_VERSION");
        public final static Property CreateTime = new Property(8, java.util.Date.class, "createTime", false, "CREATE_TIME");
    }


    public LogEntityDao(DaoConfig config) {
        super(config);
    }
    
    public LogEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LOG_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CLASS_NAME\" TEXT," + // 1: className
                "\"MESSAGE\" TEXT," + // 2: message
                "\"DEVICE_BRAND\" TEXT," + // 3: deviceBrand
                "\"MODEL\" TEXT," + // 4: model
                "\"SDK\" INTEGER NOT NULL ," + // 5: sdk
                "\"IMEI\" TEXT," + // 6: imei
                "\"SYSTEM_VERSION\" TEXT," + // 7: systemVersion
                "\"CREATE_TIME\" INTEGER);"); // 8: createTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LOG_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LogEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String className = entity.getClassName();
        if (className != null) {
            stmt.bindString(2, className);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(3, message);
        }
 
        String deviceBrand = entity.getDeviceBrand();
        if (deviceBrand != null) {
            stmt.bindString(4, deviceBrand);
        }
 
        String model = entity.getModel();
        if (model != null) {
            stmt.bindString(5, model);
        }
        stmt.bindLong(6, entity.getSdk());
 
        String imei = entity.getImei();
        if (imei != null) {
            stmt.bindString(7, imei);
        }
 
        String systemVersion = entity.getSystemVersion();
        if (systemVersion != null) {
            stmt.bindString(8, systemVersion);
        }
 
        java.util.Date createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(9, createTime.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LogEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String className = entity.getClassName();
        if (className != null) {
            stmt.bindString(2, className);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(3, message);
        }
 
        String deviceBrand = entity.getDeviceBrand();
        if (deviceBrand != null) {
            stmt.bindString(4, deviceBrand);
        }
 
        String model = entity.getModel();
        if (model != null) {
            stmt.bindString(5, model);
        }
        stmt.bindLong(6, entity.getSdk());
 
        String imei = entity.getImei();
        if (imei != null) {
            stmt.bindString(7, imei);
        }
 
        String systemVersion = entity.getSystemVersion();
        if (systemVersion != null) {
            stmt.bindString(8, systemVersion);
        }
 
        java.util.Date createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindLong(9, createTime.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LogEntity readEntity(Cursor cursor, int offset) {
        LogEntity entity = new LogEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // className
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // message
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // deviceBrand
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // model
            cursor.getInt(offset + 5), // sdk
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // imei
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // systemVersion
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)) // createTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LogEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setClassName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMessage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDeviceBrand(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setModel(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSdk(cursor.getInt(offset + 5));
        entity.setImei(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSystemVersion(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCreateTime(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LogEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LogEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LogEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
